# Generated by Django 3.0.8 on 2020-07-26 17:56

import appadmin.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(choices=[('AGRA', 'Agra'), ('AHMEDABAD', 'Ahmedabad'), ('ALAPPUZHA', 'Alappuzha'), ('ALWAR', 'Alwar'), ('AMRITSAR', 'Amritsar'), ('AURANGABAD', 'Aurangabad'), ('BANGALORE', 'Bangalore'), ('BHARATPUR', 'Bharatpur'), ('BHAVANAGAR', 'Bhavnagar'), ('BHIKANER', 'Bhikaner'), ('BHOPAL', 'Bhopal'), ('BHUBANESHWAR', 'Bhubaneshwar'), ('BODH GAYA', 'Bodh Gaya'), ('CALANGUTE', 'Calangute'), ('CHANDIGARH', 'Chandigarh'), ('CHENNAI', 'Chennai'), ('CHITTAURGARH', 'Chittaurgarh'), ('COIMBATHORE', 'Coimbatore'), ('CUTTACK', 'Cuttack'), ('DALHOUSIE', 'Dalhousie'), ('DEHRADUN', 'Dehradun'), ('DELHI', 'Delhi'), ('DIU_ISLAND', 'Diu - Island'), ('ERNAKULAM', 'Ernakulam'), ('FARIDABAD', 'Faridabad'), ('GAYA', 'Gaya'), ('GANGTOK', 'Gangtok'), ('GHAZIBAD', 'Ghaziabad'), ('GURGAON', 'Gurgaon'), ('GUWAHATI', 'Guwahati'), ('GWALIOR', 'Gwalior'), ('HARIDWAR', 'Haridwar'), ('HYDERABAD', 'Hyderabad'), ('IMPHAL', 'Imphal'), ('INDORE', 'Indore'), ('JBALPUR', 'Jabalpur'), ('JAIPUR', 'Jaipur'), ('JAISALMAR', 'Jaisalmer'), ('JALANDHAR', 'Jalandhar'), ('JAMSHEDPUR', 'Jamshedpur'), ('JODHPUR', 'Jodhpur'), ('JANAGARH', 'Junagadh'), ('KANPUR', 'Kanpur'), ('KANYAKUMARI', 'Kanyakumari'), ('KHAJURAHO', 'Khajuraho'), ('KHANDALA', 'Khandala'), ('KOCHI', 'Kochi'), ('KODAIKANAL', 'Kodaikanal'), ('KILKATA', 'kolkata'), ('KOTA', 'Kota'), ('KOTTAYAM', 'Kottayam'), ('KOVALAM', 'Kovalam'), ('LUCKNOW', 'Lucknow'), ('LUDHIANA', 'Ludhiana'), ('MADURAI', 'Madurai'), ('MANALI', 'Manali'), ('MANGALORE', 'Mangalore'), ('MARGAO', 'Margao'), ('MATHURA', 'Mathura'), ('MOUNRABU', 'Mountabu'), ('MUMBAI', 'Mumbai'), ('MUSSORIE', 'Mussoorie'), ('MYSORE', ' Mysore'), ('MANALI', 'Manali'), ('NAGPUR', 'Nagpur'), ('NAINITAL', 'Nainital'), ('NOIDA', 'Noida'), ('OOTY', 'Ooty'), ('ORCHHA', 'Orchha'), ('PANAJI', 'Panaji'), ('PATNA', 'Patna'), ('PONDICHERRY', 'Pondicherry'), ('PORBANDAR', 'Porbandar'), ('PORTBLAIR', 'Portblair'), ('PUNE', 'Pune'), ('PURI', 'Puri'), ('PUSHKAR', 'Pushkar'), ('RAJKOT', 'Rajkot'), ('RAMESHWARAM', 'Rameswaram'), ('RANCHI', 'Ranchi'), ('SANCHI', 'Sanchi'), ('SECUNDERABAD', 'Secunderabad'), ('SHIMLA', 'Shimla'), ('SURAT', 'Surat'), ('THAJAVUR', 'Thanjavur'), ('THIRUCHIRAPALLI', 'Thiruchchirapalli'), ('THRISSUR', 'Thrissur'), ('TIRUMALA', 'Tirumala'), ('UDAIPUR', 'Udaipur'), ('VADODRA', 'Vadodra'), ('VARANASI', 'Varanasi'), ('VASCO-DA-GAMA', 'Vasco - Da - Gama'), ('VIJAYAWADA', 'Vijayawada'), ('VISAKHAPATNAM', 'Visakhapatnam')], max_length=100)),
                ('address', models.CharField(default='', max_length=250)),
                ('otp', models.CharField(max_length=200, null=True)),
                ('otp_gen_time', models.DateTimeField()),
                ('token', models.CharField(default='', max_length=200)),
                ('account_creation', appadmin.models.CustomDateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
