# Generated by Django 3.0.8 on 2020-07-26 04:23

import appadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('people_involve', models.IntegerField(default=0)),
                ('account_creation', appadmin.models.CustomDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
