# Generated by Django 3.0.8 on 2020-07-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessuser', '0002_auto_20200726_2347'),
        ('appadmin', '0002_business_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Service_info',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_price', models.IntegerField(default=0)),
                ('Profession_Experience', models.IntegerField(default=0)),
                ('ServiceProvider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buisnessuser.Professional_user')),
                ('service_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.Business_Service')),
            ],
        ),
    ]
